language: cpp
git:
  depth: false
cache:
  ccache: true
  directories: 
    - "$HOME/Library/Caches/Homebrew"
if: fork = true OR type = api
matrix:
  include:
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='amazonlinux-2'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='centos-7.6'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='ubuntu-16.04'
    - os: linux
      dist: xenial
      services: docker
      env:
        - IMAGE_TAG='ubuntu-18.04'
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          update: true
          packages:
            - boost@1.70
            - ccache
script: "./.cicd/run.sh"
notifications:
  webhooks:
    secure: n0VHgAzeIqcnitJBX+UMdrnbUZQ3Nh/CvVj2I4E5FhjoolzM0pRmnPQ4h6BQ/QwTdGPh1AbitDDDGRCSGtZH2erp9OFv+gePZyaRN/+h0Q3Ak8hwfqr7UoEUcJuPFA6S42TduCs6Kn+1XnL5g2OZYAmlS9+H7MvjUqFloa0YL/F8RJ4rvXVtMsHbC6bKXSBwVROU8G4rq8zNnNShL91i5xakhywfLkhgmRM/xuL4I+7+5LXJwOvnQMQnyL55NdREmvvwJqjHNBPvjTe1Rm2xQpC5+gxW2ZaqtjuulwY/IJgWWhUlJhrZTiBpf6v3camqdFxAjA+7fGDiZNXGe4xgZuEojj++2oM6orGhGc58Pr015lxGgcLF7d7+sqINCEnTVtleSC7czsnkcpONVOyi9BW2Gyxjaf2EN09/XH3QzH093WkOeEhREwMUo7Xa2ugu/svnqp890FTgGftUY0dJkOP8v3y+sU9DQ9/CwcsRIzFBfoZFOL0OySM9+nH4Ervkf5z8n1ikGHjE6xv63P1nV7SmrTjnIGgJ60xYFtPgV0ELBmy4cbVF86Jcr8KrTPhna3wgXX80g8UOgZlVIUOErvhJWxThW6wz2PO07QU5Y+caz0zrL2c7AuXXn5BQjtMPBSIomOybgFyrP0Yf6qKBXTV4Y3qEpiYa/PkZvxUsT6U=