language: cpp
git:
  depth: false
cache:
  ccache: true
  directories:
  - "$HOME/Library/Caches/Homebrew"
matrix:
  include:
  - os: linux
    dist: xenial
    services: docker
    env:
    - IMAGE_TAG='ubuntu-18.04'
script:
- "./.cicd/travis-build.sh"
env:
  global:
    secure: pVEWl7chHX4rjz8sfKTMJ1xY56kUKkzMsWJKq7S0GBEc81C3obS9qlq9nQr3DxyeLiDjnnnhJcaEYLD8mGHYapGC4ellsTpTO1l+8UeTuhMZTcJvE6BpzCNva4OyoThP7w3kmw/SCAXSdmcJns/PlKhmqjlg/6FcW85Nnbz0QZ4wNiaQA//QwLUIbPE1CUqzupesRUmicWor3HIdB4+EO1uCnb2lO3p1tUlEg8zuHl856HZ7BjPqB7o/LfGeofFbdDXharV5mJnIP6/o3UxfVbjcR0WkhnD27Wf0QWc3IiUt8wv1dN8ay39TEhcmiba62b9D1yVz01jneuxIf4x2OJ+o+IRDNmivn+gtUPOODJHABJ8n4xiCslGoa25r3FDQj6JxCWaPa/8fj7FbbxHh0+PZm81s0KxUB/d6CqXBirk8wvkFEDHrx/A1UXX6EtGltnGiM7lm7yCfZfbhbz4qxflT/2aChFzRWCHXAwenunN1I7tO9h9HiwGPpvJDuP1uo8dh1sV7wpVARxMy04JWx6y/A6tI6Ksny5JSdCKu/MNOlhL+DApYVJuyWPqw5naDVTfdjMCRz3f6W2IkR0aj0xgdUw9S15K0ILMBB2FUjMHSngpmYGxYTROjqoj4n8IwiQ5Urb+sBsXZfOmNq1qKpFH3xcNw9U/GTAdOc+hM+vk=
