steps:
  - wait

  - label: ":webhook: Trigger Travis CI Build"
    command: |
      . ./.cicd/trigger-travis.sh
    agents:
      queue: "automation-basic-builder-fleet"
    timeout: ${TIMEOUT:-2}

  - trigger: "eos-vm-base-images-beta"
    label: ":docker: Docker - Ensure Base Images Exist"
    build:
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"

  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eos-vm-amazonlinux-2-63e818cb623e802d26101fb47d6c0b0e1cf5ddef"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.2.0:
          debug: $DEBUG
          image: "eosio/producer:eos-vm-ubuntu-16.04-652bfca060ffe0f01701dcadc4a92f2d1ff1651c"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    agents:
      queue: "automation-eos-builder-fleet"
    plugins:
      - docker#v3.3.0:
          debug: $DEBUG
          image: "eosio/producer:eos-vm-ubuntu-18.04-910b4e4a97a4ee8d45f304528d536d9c4425238a"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18