steps:

  - label: ":aws: Amazon_Linux 2 - Build"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
      ENABLE_BUILD: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.6 - Build"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "centos-7.6"
      ENABLE_BUILD: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "ubuntu-16.04"
      ENABLE_BUILD: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      ENABLE_BUILD: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "brew install git cmake boost ccache"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos-vm && ENABLE_BUILD=true ./.cicd/run.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-large-node-fleet"

  - wait

  - label: ":aws: Amazon_Linux 2 - Test"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
      ENABLE_TEST: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_AMAZON_LINUX_2

  - label: ":centos: CentOS 7.6 - Test"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "centos-7.6"
      ENABLE_TEST: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_CENTOS_7

  - label: ":ubuntu: Ubuntu 16.04 - Test"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "ubuntu-16.04"
      ENABLE_TEST: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_16

  - label: ":ubuntu: Ubuntu 18.04 - Test"
    command:
      - "bash ./.cicd/run.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
      ENABLE_TEST: true
    agents: 
      queue: "automation-eos-builder-fleet"
    timeout: ${TIMEOUT:-10}
    skip: $SKIP_UBUNTU_18

  - label: ":darwin: macOS 10.14 - Tests"
    command:
      - "brew install git cmake ccache"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git submodule update --init --recursive"
      - "cd eos-vm && buildkite-agent artifact download build.tar.gz . --step ':darwin: macOS 10.14 - Build' && tar -xzf build.tar.gz"
      - "cd eos-vm && ENABLE_TEST=true ./.cicd/run.sh"
    plugins:
      - chef/anka#v0.5.1:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.4_6C_14G_40G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-node-fleet"
