steps:
  - wait

  - label: ":aws: Amazon_Linux 2 - Build"
    command: "./.cicd/build.sh"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_AMAZON_LINUX_2$SKIP_LINUX

  - label: ":centos: CentOS 7.7 - Build"
    command: "./.cicd/build.sh"
    env:
      IMAGE_TAG: "centos-7.7"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_CENTOS_7$SKIP_LINUX

  - label: ":ubuntu: Ubuntu 16.04 - Build"
    command: "./.cicd/build.sh"
    env:
      IMAGE_TAG: "ubuntu-16.04"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_16$SKIP_LINUX

  - label: ":ubuntu: Ubuntu 18.04 - Build"
    command: "./.cicd/build.sh"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_UBUNTU_18$SKIP_LINUX

  - label: ":darwin: macOS 10.14 - Build"
    command:
      - "brew update && brew upgrade"
      - "brew install git cmake"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos-vm && ./.cicd/build.sh"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.6_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-large-node-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_MACOS_10_14$SKIP_MAC

  - label: ":darwin: macOS 10.15 - Build"
    command:
      - "brew update && brew upgrade"
      - "brew install git cmake"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos-vm && ./.cicd/build.sh"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          modify-cpu: 12
          modify-ram: 24
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-large-node-fleet"
    timeout: $BUILD_TIMEOUT
    skip: $SKIP_MACOS_10_15$SKIP_MAC

  - wait

  - label: ":aws: Amazon_Linux 2 - Test"
    command: "./.cicd/test.sh ':aws: Amazon_Linux 2 - Build'"
    env:
      IMAGE_TAG: "amazonlinux-2"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_AMAZON_LINUX_2$SKIP_LINUX

  - label: ":centos: CentOS 7.7 - Test"
    command: "./.cicd/test.sh ':centos: CentOS 7.7 - Build'"
    env:
      IMAGE_TAG: "centos-7.7"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_CENTOS_7$SKIP_LINUX

  - label: ":ubuntu: Ubuntu 16.04 - Test"
    command: "./.cicd/test.sh ':ubuntu: Ubuntu 16.04 - Build'"
    env:
      IMAGE_TAG: "ubuntu-16.04"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_UBUNTU_16$SKIP_LINUX

  - label: ":ubuntu: Ubuntu 18.04 - Test"
    command: "./.cicd/test.sh ':ubuntu: Ubuntu 18.04 - Build'"
    env:
      IMAGE_TAG: "ubuntu-18.04"
    agents: 
      queue: "automation-eks-eos-builder-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_UBUNTU_18$SKIP_LINUX

  - label: ":darwin: macOS 10.14 - Test"
    command:
      - "brew update && brew upgrade"
      - "brew install git cmake"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos-vm && ./.cicd/test.sh ':darwin: macOS 10.14 - Build'"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.14.6_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-node-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_MACOS_10_14$SKIP_MAC

  - label: ":darwin: macOS 10.15 - Test"
    command:
      - "brew update && brew upgrade"
      - "brew install git cmake"
      - "git clone $BUILDKITE_REPO eos-vm && cd eos-vm && git checkout $BUILDKITE_COMMIT && git submodule update --init --recursive"
      - "cd eos-vm && ./.cicd/test.sh ':darwin: macOS 10.15 - Build'"
    plugins:
      - EOSIO/anka#v0.6.0:
          no-volume: true
          inherit-environment-vars: true
          vm-name: 10.15.5_6C_14G_80G
          vm-registry-tag: "clean::cicd::git-ssh::nas::brew::buildkite-agent"
          always-pull: true
          debug: true
          wait-network: true
    agents: "queue=mac-anka-node-fleet"
    timeout: $TEST_TIMEOUT
    skip: $SKIP_MACOS_10_15$SKIP_MAC

  - wait:
    continue_on_failure: true

  - label: ":bar_chart: Test Metrics"
    command: |
      echo '+++ :compression: Extracting Test Metrics Code'
      tar -zxf .cicd/metrics/test-metrics.tar.gz
      echo '+++ :javascript: Running test-metrics.js'
      node --max-old-space-size=32768 test-metrics.js
    agents:
      queue: "automation-eks-eos-builder-fleet"
    timeout: 10
    soft_fail: true
