

(module
  (type $ret-i32 (func (param i32) (result i32)))
  (func $host.test (import "host" "test") (param i32) (result i32))
  (memory 1)
  (table 2 2 anyfunc)
  (func $local.test (export "test") (param i32) (result i32)
    (get_local 0)
    (call $host.test)
    (i32.const 2)
    (i32.add)
  )
  (func (export "test.indirect") (param i32 i32) (result i32)
    (get_local 0)
    (get_local 1)
    (call_indirect (type $ret-i32))
  )
  (elem (i32.const 0) 0 1)
)
